### ISSUE TITLE
allow user to adjust hmax, maxsteps, atol, and rtol in the simulation when needed to make it more flexible (under "solver settings") 

### ISSUE THREAD

**Issue by andersone1** [Genentech/gPKPDviz#4]
https://8a46b168e1254af78add5bdbc79ad8ac.metworx.com/rstudio/s/7d2ab690e86183d960361/help/library/mrgsolve/html/update.html

**Comment by andersone1** [comment]
@tonggne 

## The following model inputs will be added:
- hmax
- maxsteps
- rtol

## The input "atol" already exists:
<img width="751" alt="image" src="https://github.com/Genentech/gPKPDviz/assets/28537780/8f8c10ac-4a8f-41b3-9346-72316510979f">

**Comment by andersone1** [comment]
@tonggne - 

Do you have input type preferences for these (sliders?):

- hmax
- maxsteps
- rtol

**Comment by tonggne** [comment]
slider input will be are good.

**Comment by andersone1** [comment]
@tonggne 

Here is the underlying input for `atol`:

```
sliderInput(
     "aTolValue",
      label = "Absolute Solver Tolerance Value (1e-'Value')",
      min = 1,
      max = 50,
      step = 1,
      value = 30
)
```

and then here is how it gets used in the simulation call (`mrgsim()`):
`atol = as.numeric(paste0("1E-", input$aTolValue))`

If you don't mind, can you specify:

- label
- min 
- max
- step
- value

for 

- hmax
- maxsteps
- rtol

and also if the `1E-` method applies to any of them.

**Comment by tonggne** [comment]
that make sense to me. Thanks!

**Comment by tonggne** [comment]
sorry Eric, I missed read your message. Here is what you need:

**rtol:**
 label: Relative tolerance
 min = 1,
 max = 30,
 step = 1,
 value = 8,
 transformation: "paste0("1E-", rtol))"

**maxsteps**
 label:  Maximum number of steps
 min = 10,
 max = 80,
 step = 5,
 value = 20,
 transformation: "maxsteps * 1000"

**hmax**
 label:  maximum step size
given that the default value of hmax would depend on what is happening in the simulation (case-by-case). Slider might not be a good idea. The numerical input by the users is better in this case. If not defined by the users (left blank), the default value would be used.

**Comment by andersone1** [comment]
Perfect, thanks Tong.

**Comment by andersone1** [comment]
@tonggne , speaking with kyle we had a couple changes for the default & min/max values of `atol` and `rtol`:

```
atol:
min = 5
max = 50
default value = 8
```

```
rtol:
min = 2
max = 16
default value = 8
```

**Comment by tonggne** [comment]
Sure, thanks Eric! How about the step, would that still be 1?

**Comment by andersone1** [comment]
@tonggne Yes, the step stays at 1

**Comment by tonggne** [comment]
Thanks!
